In [ ]:
#lab16
import pandas as pd
import numpy as np

In [35]:
data = { 
    'Order_ID': ['1001', '1002', '1003', '1004', '1005'], 
    'Product_ID': ['P101', 'P102', 'P103', 'P101', 'P104'], 
    'Product_Name': ['Laptop', 'Smartphone', 'Headphones', 'Laptop', 'Coffee Maker'], 
    'Category': ['Electronics', 'Electronics', 'Accessories', 'Electronics', 'Kitchen'], 
    'Quantity': [2, 1, 5, 3, 2], 
    'Amount': [1600, 600, 500, 2400, 100], 
    'Date': ['2024-01-10', '2024-01-11', '2024-01-12', '2024-01-12', '2024-01-13'], 
    'Region': ['North', 'South', 'East', 'West', 'North'], 
} 
dataset = pd.DataFrame(data) 
dataset

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North

In [36]:
ds = dataset[['Product_Name', 'Amount']]
ds

   Product_Name  Amount
0        Laptop    1600
1    Smartphone     600
2    Headphones     500
3        Laptop    2400
4  Coffee Maker     100

In [37]:
salesabove_1000 = dataset[dataset.Amount >= 1000]
salesabove_1000

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West

In [38]:
sales = dataset[(dataset["Amount"] >= 500) & (dataset["Region"].isin(["East", "South"]))]
print(sales)

  Order_ID Product_ID Product_Name     Category  Quantity  Amount        Date  \
1     1002       P102   Smartphone  Electronics         1     600  2024-01-11
2     1003       P103   Headphones  Accessories         5     500  2024-01-12

  Region
1  South
2   East

In [39]:
sales = dataset.groupby('Product_Name')['Amount'].sum()
print("total amount for each product:", sales)

total amount for each product: Product_Name
Coffee Maker     100
Headphones       500
Laptop          4000
Smartphone       600
Name: Amount, dtype: int64

In [ ]:
sales = dataset[(pd.to_datetime(dataset["Date"]) > "2024-01-10") &
(pd.to_datetime(dataset["Date"]) < "2024-01-13")]
sales

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West

In [41]:
dataset['Total'] = dataset['Quantity'] * dataset['Amount']
dataset

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region,Total
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North,3200
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South,600
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East,2500
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West,7200
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North,200

In [43]:
dataset['Tax'] = dataset['Amount'] * 0.15
dataset

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region,Total,Tax
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North,3200,240.0
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South,600,90.0
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East,2500,75.0
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West,7200,360.0
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North,200,15.0

In [44]:
dataset['Net_sales'] = dataset['Total'] - dataset['Tax']
dataset

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region,Total,Tax,Net_sales
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North,3200,240.0,2960.0
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South,600,90.0,510.0
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East,2500,75.0,2425.0
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West,7200,360.0,6840.0
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North,200,15.0,185.0

In [78]:
data = { 
    'Student_ID': ['S001', 'S002', 'S003', 'S004', 'S005'], 
    'Mathematics' : [85, 75, 95, 65, 90], 
    'Science' : [78, 88, 82, 85, 79], 
    'English' : [90, 85, 80, 70, 95], 
    'IT' : [89, 65, 88, 92, 98] 
} 
result = pd.DataFrame(data) 
result

  Student_ID  Mathematics  Science  English  IT
0       S001           85       78       90  89
1       S002           75       88       85  65
2       S003           95       82       80  88
3       S004           65       85       70  92
4       S005           90       79       95  98

In [79]:
result["Average"] = result[["Mathematics", "Science", "English", "IT"]].mean(axis=1)
result

  Student_ID  Mathematics  Science  English  IT  Average
0       S001           85       78       90  89    85.50
1       S002           75       88       85  65    78.25
2       S003           95       82       80  88    86.25
3       S004           65       85       70  92    78.00
4       S005           90       79       95  98    90.50

In [80]:
result['Weight_Average'] = (
    result['Mathematics'] * 0.4 +
    result['Science'] * 0.2 +
    result['English'] * 0.2 +
    result['IT'] * 0.2
)

result

  Student_ID  Mathematics  Science  English  IT  Average  Weight_Average
0       S001           85       78       90  89    85.50            85.4
1       S002           75       88       85  65    78.25            77.6
2       S003           95       82       80  88    86.25            88.0
3       S004           65       85       70  92    78.00            75.4
4       S005           90       79       95  98    90.50            90.4

In [81]:
def standardize(column):
    mean = np.mean(column)
    std_dev = np.std(column)
    return (column - mean) / std_dev

result['Math_std'] = standardize(result['Mathematics'])
result['sci_std'] = standardize(result['Science'])
result['Eng_std'] = standardize(result['English'])
result['IT_std'] = standardize(result['IT'])
result

,Student_ID,Mathematics,Science,English,IT,Average,Weight_Average,Math_std,sci_std,Eng_std,IT_std
0,S001,85,78,90,89,85.50,85.4,0.278543,-1.182727,0.697486,0.231040
1,S002,75,88,85,65,78.25,77.6,-0.649934,1.505289,0.116248,-1.901640
2,S003,95,82,80,88,86.25,88.0,1.207020,-0.107521,-0.464991,0.142179
3,S004,65,85,70,92,78.00,75.4,-1.578410,0.698884,-1.627467,0.497625
4,S005,90,79,95,98,90.50,90.4,0.742781,-0.913926,1.278724,1.030796

In [82]:
def assign_grade(weighted_avg):
    if weighted_avg >= 85:
        return 'A'
    elif weighted_avg >= 75:
        return 'B'
    elif weighted_avg >= 65:
        return 'C'
    elif weighted_avg >= 55:
        return 'D'
    else:
        return 'F'

result["Final_Grade"] = result["Weight_Average"].apply(assign_grade)
result

,Student_ID,Mathematics,Science,English,IT,Average,Weight_Average,Math_std,sci_std,Eng_std,IT_std,Final_Grade
0,S001,85,78,90,89,85.50,85.4,0.278543,-1.182727,0.697486,0.231040,A
1,S002,75,88,85,65,78.25,77.6,-0.649934,1.505289,0.116248,-1.901640,B
2,S003,95,82,80,88,86.25,88.0,1.207020,-0.107521,-0.464991,0.142179,A
3,S004,65,85,70,92,78.00,75.4,-1.578410,0.698884,-1.627467,0.497625,B
4,S005,90,79,95,98,90.50,90.4,0.742781,-0.913926,1.278724,1.030796,A